
version: "3"
services:
    build:
      build:
        context: .
        dockerfile: arduino-cli.Dockerfile
      volumes:
        - ./:/wfh_monitor
        - ./lib:/root/Arduino/libraries:ro
      command: >
        bash -c "chmod +x ./build.sh && ./build.sh"
    upload:
      build:
        context: .
        dockerfile: arduino-cli.Dockerfile
      volumes:
        - ./:/wfh_monitor
        - ./lib:/root/Arduino/libraries:ro
      devices: 
        - /dev/ttyS10:/dev/ttyTarget # ttyS10を自分のターゲットに置き換える
      command: >
        bash -c "chmod +x ./upload.sh && ./upload.sh"
    docs:
      build:
        context: .
        dockerfile: ./doxygen.Dockerfile
      volumes:
        - ./:/wfh_monitor
        - ./lib:/root/Arduino/libraries:ro
      command: doxygen