
version: "3"
services:
    build:
      build: .
      volumes:
        - ./:/work
      command: >
        bash -c "chmod +x ./build.sh && ./build.sh"
    upload:
      build: .
      volumes:
        - ./:/work
      devices: 
        - /dev/ttyS10:/dev/ttyTarget # ttyS10を自分のターゲットに置き換える
      command: >
        bash -c "chmod +x ./upload.sh && ./upload.sh"