
version: "3"
services:
    build:
      build: .
      volumes:
        - ./:/work
      command: arduino-cli compile -b Seeeduino:samd:seeed_wio_terminal ./wfh_monitor.ino --verbose --log-level trace