name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - run: docker-compose run build
    - uses: actions/upload-artifact@v2
      with:
        name: wfh_monitor.zip
        path: wfh_monitor.ino.Seeeduino.samd.seeed_wio_terminal.*
    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@v1.1.1-beta"
      with:
        REPO: ${{ github.repository }}
        BEFORE: ${{ github.event.before }}
        SHA: ${{ github.sha }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABEL: "TODO:"
        COMMENT_MARKER: "//"
      id: "todo"
