name: Common

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_todo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2     
    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@master"
      with:
        REPO: ${{ github.repository }}
        BEFORE: ${{ github.event.before }}
        SHA: ${{ github.sha }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABEL: "TODO:"
        COMMENT_MARKER: "//"
